/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorProducto;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 *
 * @author Ivnn
 */
public class VerProductos extends javax.swing.JFrame {

    /**
     * Creates new form VerProductos
     */
    public VerProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_bproducto = new javax.swing.JLabel();
        txt_ingresenombreproducto = new javax.swing.JLabel();
        txt_codigobuscado = new javax.swing.JTextField();
        btn_mostrartodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_productos = new javax.swing.JTable();
        btn_volver = new javax.swing.JButton();
        txt_buscarporcodigo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_bproducto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_bproducto.setText("Buscar Producto");

        txt_ingresenombreproducto.setText("Ingrese el Codigo del Producto");

        txt_codigobuscado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigobuscadoActionPerformed(evt);
            }
        });

        btn_mostrartodo.setText("Mostrar Todo");
        btn_mostrartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrartodoActionPerformed(evt);
            }
        });

        tbl_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Producto", "Descripcion", "Precio de venta", "Stock minimo", "Stock Actual", "Tipo de Producto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_productos);

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        txt_buscarporcodigo.setText("Buscar por codigo");
        txt_buscarporcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarporcodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_bproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_ingresenombreproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_codigobuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_buscarporcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mostrartodo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_volver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_bproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ingresenombreproducto)
                    .addComponent(txt_codigobuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_buscarporcodigo)
                    .addComponent(btn_mostrartodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_mostrartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrartodoActionPerformed
        // TODO add your handling code here:String tituloBuscado = txt_ingresarLibro.getText();
        
        String codigoBuscado = txt_codigobuscado.getText();
        //int codigoBuscado = Integer.parseInt(txt_codigobuscado.getText());
        ControladorProducto cl = new ControladorProducto();
        
        if(codigoBuscado.isEmpty())
        {
        
            ArrayList<Producto> productos = cl.traerTodo();
           
            DefaultTableModel tablaProductos = (DefaultTableModel) tbl_productos.getModel();
            tablaProductos.setRowCount(0); 
            
            for(Producto l : productos)
            {
            
                int codigo = l.getCodigo();
                String descripcion = l.getDescripcion();
                int precio = l.getPrecio();
                int stockMinimo = l.getStockMinimo();
                int stockActual = l.getStockActual();
                String tipoProducto = l.getTipoProducto();
                
                
                
                  tablaProductos.addRow(new Object[]{codigo,descripcion,precio,stockMinimo,stockActual,tipoProducto});
            }
            
        }
    }//GEN-LAST:event_btn_mostrartodoActionPerformed

    private void txt_codigobuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigobuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigobuscadoActionPerformed

    private void txt_buscarporcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarporcodigoActionPerformed
        int codigo = Integer.parseInt(txt_codigobuscado.getText());
        ControladorProducto cl = new ControladorProducto();
        Producto prod = cl.buscarProductoPorCodigo(codigo);


        DefaultTableModel modeloTabla = (DefaultTableModel) tbl_productos.getModel();
        modeloTabla.setRowCount(0);

        if (String.valueOf(prod.getCodigo())!=null)
        {
            String descripcion = prod.getDescripcion();
            int precio = prod.getPrecio();
            int stock_minimo = prod.getStockMinimo();
            int stock_actual = prod.getStockActual();
            String tipo_producto = prod.getTipoProducto();

            modeloTabla.addRow (new Object[]{codigo, descripcion, precio, stock_minimo, stock_actual, tipo_producto});


        }       
        
    }//GEN-LAST:event_txt_buscarporcodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mostrartodo;
    private javax.swing.JButton btn_volver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_bproducto;
    private javax.swing.JTable tbl_productos;
    private javax.swing.JButton txt_buscarporcodigo;
    private javax.swing.JTextField txt_codigobuscado;
    private javax.swing.JLabel txt_ingresenombreproducto;
    // End of variables declaration//GEN-END:variables
}
